name: publish
on:
  push:
    branches:
      - main
jobs:
  publish-ladle-docker-image:
    name: Publish Prayer Walk Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Prayer Walk image
        run: |
          docker build . --tag ghcr.io/lukebatchelor/prayer-walk-2023-app:latest
          docker push ghcr.io/lukebatchelor/prayer-walk-2023-app:latest
